server:
  port: 8080
  servlet:
    context-path: /api
spring:
  http:
    encoding:
      charset: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/sports?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.sport.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG